//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        inter_packet_delay_cpu_regs_defines.v
//
//  Module:
//        inter_packet_delay_cpu_regs_defines
//
//  Description:
//        This file is automatically generated with the registers defintions towards the CPU/Software
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"),
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//


`define  REG_CTRL0_BITS				31:0
`define  REG_CTRL0_WIDTH				32
`define  REG_CTRL0_DEFAULT				32'h0
`define  REG_CTRL0_ADDR				32'h0

`define  REG_CTRL1_BITS				31:0
`define  REG_CTRL1_WIDTH				32
`define  REG_CTRL1_DEFAULT				32'h0
`define  REG_CTRL1_ADDR				32'h4

`define  REG_CTRL2_BITS				31:0
`define  REG_CTRL2_WIDTH				32
`define  REG_CTRL2_DEFAULT				32'h0
`define  REG_CTRL2_ADDR				32'h8

`define  REG_CTRL3_BITS				31:0
`define  REG_CTRL3_WIDTH				32
`define  REG_CTRL3_DEFAULT				32'h0
`define  REG_CTRL3_ADDR				32'hC

`define  REG_CTRL4_BITS				31:0
`define  REG_CTRL4_WIDTH				32
`define  REG_CTRL4_DEFAULT				32'h0
`define  REG_CTRL4_ADDR				32'h10

`define  REG_CTRL5_BITS				31:0
`define  REG_CTRL5_WIDTH				32
`define  REG_CTRL5_DEFAULT				32'h0
`define  REG_CTRL5_ADDR				32'h14

`define  REG_CTRL6_BITS				31:0
`define  REG_CTRL6_WIDTH				32
`define  REG_CTRL6_DEFAULT				32'h0
`define  REG_CTRL6_ADDR				32'h18

`define  REG_CTRL7_BITS				31:0
`define  REG_CTRL7_WIDTH				32
`define  REG_CTRL7_DEFAULT				32'h0
`define  REG_CTRL7_ADDR				32'h1C

`define  REG_CTRL8_BITS				31:0
`define  REG_CTRL8_WIDTH				32
`define  REG_CTRL8_DEFAULT				32'h0
`define  REG_CTRL8_ADDR				32'h20

`define  REG_CTRL9_BITS				31:0
`define  REG_CTRL9_WIDTH				32
`define  REG_CTRL9_DEFAULT				32'h0
`define  REG_CTRL9_ADDR				32'h24

`define  REG_CTRL10_BITS				31:0
`define  REG_CTRL10_WIDTH				32
`define  REG_CTRL10_DEFAULT				32'h0
`define  REG_CTRL10_ADDR				32'h28

`define  REG_CTRL11_BITS				31:0
`define  REG_CTRL11_WIDTH				32
`define  REG_CTRL11_DEFAULT				32'h0
`define  REG_CTRL11_ADDR				32'h2C

`define  REG_CTRL12_BITS				31:0
`define  REG_CTRL12_WIDTH				32
`define  REG_CTRL12_DEFAULT				32'h0
`define  REG_CTRL12_ADDR				32'h30

`define  REG_CTRL13_BITS				31:0
`define  REG_CTRL13_WIDTH				32
`define  REG_CTRL13_DEFAULT				32'h0
`define  REG_CTRL13_ADDR				32'h34

`define  REG_CTRL14_BITS				31:0
`define  REG_CTRL14_WIDTH				32
`define  REG_CTRL14_DEFAULT				32'h0
`define  REG_CTRL14_ADDR				32'h38

`define  REG_CTRL15_BITS				31:0
`define  REG_CTRL15_WIDTH				32
`define  REG_CTRL15_DEFAULT				32'h0
`define  REG_CTRL15_ADDR				32'h3C