//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        packet_cutter_cpu_regs_defines.v
//
//  Module:
//        packet_cutter_cpu_regs_defines
//
//  Description:
//        This file is automatically generated with the registers defintions towards the CPU/Software
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"),
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//


`define  REG_CTRL_REGS0_BITS				31:0
`define  REG_CTRL_REGS0_WIDTH				32
`define  REG_CTRL_REGS0_DEFAULT				32'h0
`define  REG_CTRL_REGS0_ADDR				32'h0

`define  REG_CTRL_REGS1_BITS				31:0
`define  REG_CTRL_REGS1_WIDTH				32
`define  REG_CTRL_REGS1_DEFAULT				32'h0
`define  REG_CTRL_REGS1_ADDR				32'h4

`define  REG_CTRL_REGS2_BITS				31:0
`define  REG_CTRL_REGS2_WIDTH				32
`define  REG_CTRL_REGS2_DEFAULT				32'h0
`define  REG_CTRL_REGS2_ADDR				32'h8

`define  REG_CTRL_REGS3_BITS				31:0
`define  REG_CTRL_REGS3_WIDTH				32
`define  REG_CTRL_REGS3_DEFAULT				32'h0
`define  REG_CTRL_REGS3_ADDR				32'hC

`define  REG_CTRL_REGS4_BITS				31:0
`define  REG_CTRL_REGS4_WIDTH				32
`define  REG_CTRL_REGS4_DEFAULT				32'h0
`define  REG_CTRL_REGS4_ADDR				32'h10

`define  REG_RETURN_REGS0_BITS				31:0
`define  REG_RETURN_REGS0_WIDTH				32
`define  REG_RETURN_REGS0_DEFAULT				32'h0
`define  REG_RETURN_REGS0_ADDR				32'h18

`define  REG_RETURN_REGS1_BITS				31:0
`define  REG_RETURN_REGS1_WIDTH				32
`define  REG_RETURN_REGS1_DEFAULT				32'h0
`define  REG_RETURN_REGS1_ADDR				32'h1C